### PR TITLE
Fix return status

### PR DESCRIPTION
**Pull request by TheFirstAvenger**

### CODE REVIEW

**Comment by msawka** [comment]
* from [here](https://github.com/OpenAperture/manager/pull/15/files#diff-49b303464ac624a307792ddfbbdf531eR326), we'll also need to update the manager_api, and other components with the new status code.

**Comment by TheFirstAvenger** [comment]
@msawka From what I can see, workflow_api doesn't call the execute endpoint. I believe it is only iRobot that would call that, right?
https://github.com/OpenAperture/manager_api/blob/master/lib/openaperture_manager_api/workflow.ex

**Comment by msawka** [comment]
and the ui would be the 2 spots that are consuming it

**Comment by TheFirstAvenger** [comment]
@msawka Looks like manager ui already accepts 202 and 204:
https://github.com/OpenAperture/manager-ui/blob/master/app/scripts/services/workflow.js#L59

**Pull request merged**
