### PR TITLE
Resource cache

### PR DESCRIPTION
**Pull request by TheFirstAvenger**

### CODE REVIEW

**Comment by msawka** [comment]
* Can you add some module and function exdoc?
* The default value for :cache_queue_monitor_autostart is set to [true](https://github.com/OpenAperture/manager/pull/43/files#diff-2fb1a73f741905d9fbeeea30ac3494adR10), so you don't need to set it to true in the [prod](https://github.com/OpenAperture/manager/pull/43/files#diff-2b452058d95c3d5c86dc197bb66d1627R44) (the value wasn't being set in staging) configs.  I would move this [false](https://github.com/OpenAperture/manager/pull/43/files#diff-de9210b77e43a621a256d7a37fc5f50aR28) definition into the test config.
* ManagerQueueSubscriber
  * Let's rename it to simply ManagerQueue, since it's an abstraction on top of the queue connection logic
  * Since this is in the messaging folder, the module def for this class should include .Messaging, so OpenAperture.Manager.Messaging.ManagerQueue
  * Let's rename [subscribe_manager_queue](https://github.com/OpenAperture/manager/pull/43/files#diff-23bd18f7fb4a181b66b392ef34f16e2eR16) to simply subscribe.  
  *[Here](https://github.com/OpenAperture/manager/pull/43/files#diff-23bd18f7fb4a181b66b392ef34f16e2eR29), we need to add the try/after logic to ensure that acknowledge is called.  You can see the Overseer's [dispatcher](https://github.com/OpenAperture/overseer/blob/740d3f11d83420a2310c0d730802133f0b7f64fc/lib/overseer/dispatcher.ex#L84-L136) as an example (although I could create a method to generate those events rather than paste the block over and over again like I've done previously).  If an exception occurs and the message isn't acknowledged, it will get stuck in AMQP.
  * Let's rename [get_exchange_model](https://github.com/OpenAperture/manager/pull/43/files#diff-23bd18f7fb4a181b66b392ef34f16e2eR35) to messaging_exchange, since having "model" in the name would indicate that we're returning the db model, but it's actually returning a Messaging struct.
  * Can [this](https://github.com/OpenAperture/manager/pull/43/files#diff-23bd18f7fb4a181b66b392ef34f16e2eR36) be cached?
  * Can [this](https://github.com/OpenAperture/manager/pull/43/files#diff-23bd18f7fb4a181b66b392ef34f16e2eR47) be cached?
  * Let's rename [get_connection_options](https://github.com/OpenAperture/manager/pull/43/files#diff-23bd18f7fb4a181b66b392ef34f16e2eR60) to messaging_connection_options to stay in sync with the naming convention above.
  * Can [this](https://github.com/OpenAperture/manager/pull/43/files#diff-23bd18f7fb4a181b66b392ef34f16e2eR61) be cached?
  * Can [this](https://github.com/OpenAperture/manager/pull/43/files#diff-23bd18f7fb4a181b66b392ef34f16e2eR76) be cached?
* ResourceCache
  * Let's rename it to simply CachedResource, the idea being that each model can be cached/flushed via this module.
  * Since this is in the resource_cache folder, the module def for this class should include .ResourceCache, so OpenAperture.Manager.ResourceCache.CachedResource
  * Let's get rid of specific [types](https://github.com/OpenAperture/manager/pull/43/files#diff-df74b0c4ea2357797f8d71282ae97febR8) in favor of using the model's module name, since it's an atom already.  In cases where there isn't a specific module name, we can define custom atoms.  This should eliminate the need to validate the type being cached ([validate_type](https://github.com/OpenAperture/manager/blob/resource_cache/lib/manager/resource_cache/resource_cache.ex#L45-L55)).
  * For [log messages](https://github.com/OpenAperture/manager/pull/43/files#diff-df74b0c4ea2357797f8d71282ae97febR12), let's define a standard log prefix, something like the Overseer's [dispatcher prefix](https://github.com/OpenAperture/overseer/blob/master/lib/overseer/dispatcher.ex#L24).
  * I'm not sure I see the need for a [clear_local](https://github.com/OpenAperture/manager/blob/resource_cache/lib/manager/resource_cache/resource_cache.ex#L25-L31) vs. simply a [clear](https://github.com/OpenAperture/manager/blob/resource_cache/lib/manager/resource_cache/resource_cache.ex#L18-L23).  Anytime we need to clear a cached object, we should clear globally and replace locally.  If you want to keep the logic for local clearing separate, let's make it a private method.
  * I'm not sure I see the need for [wipe_all_caches](https://github.com/OpenAperture/manager/blob/resource_cache/lib/manager/resource_cache/resource_cache.ex#L33-L43).  It looks like the only place that's cached is during tests, but the tests could basically execute this logic.  For a Manager developer, I think it would be confusing to see these last couple of methods without a reason to call them in development.
* ResourceCacheQueueBroadcaster
    * Let's rename it to simply Publisher, similar to the convention we already have for publishing messages to queues (i.e. the [Notifications publisher](https://github.com/OpenAperture/manager/blob/resource_cache/lib/manager/notifications/publisher.ex))
  * Since this is in the resource_cache folder, the module def for this class should include .ResourceCache, so OpenAperture.Manager.ResourceCache.Publisher
  * Let's rename [broadcast_cache_clear](https://github.com/OpenAperture/manager/blob/resource_cache/lib/manager/resource_cache/resource_cache_queue_broadcaster.ex#L19) to clear_cache.
  * We already have ManagerQueue [methods](https://github.com/OpenAperture/manager/blob/resource_cache/lib/manager/messaging/manager_queue_subscriber.ex#L60-L90) to get the [connection options](https://github.com/OpenAperture/manager/blob/resource_cache/lib/manager/resource_cache/resource_cache_queue_broadcaster.ex#L39-L42) from the database, rather an api call.
  * You could potential abstract the [queue building](https://github.com/OpenAperture/manager/pull/43/files#diff-23bd18f7fb4a181b66b392ef34f16e2eR24) into a separate method and use that [here](https://github.com/OpenAperture/manager/blob/resource_cache/lib/manager/resource_cache/resource_cache_queue_broadcaster.ex#L38) as well.
  *[Here](https://github.com/OpenAperture/manager/blob/resource_cache/lib/manager/resource_cache/resource_cache_queue_broadcaster.ex#L20-L21), can you break this into a separate method called manager_components for readability?  I would also query specifically for the type of manager, see [here](https://github.com/OpenAperture/manager/blob/resource_cache/web/controllers/system_components.ex#L64).  That should cut down on your query time.
  * Let's rename [broadcast_to_queue](https://github.com/OpenAperture/manager/blob/resource_cache/lib/manager/resource_cache/resource_cache_queue_broadcaster.ex#L34) to publish to keep with the messaging conventions.

**Comment by TheFirstAvenger** [comment]
Changes submitted. Will add docs and moduledocs tomorrow AM.

Notes:

 * MessagingExchange is not yet added to the list of cachable items (so far only brokers), which is why the items you noted are not cached yet.

 * *Let's get rid of specific types in favor of using the model's module name, since it's an atom already. In cases where there isn't a specific module name, we can define custom atoms. This should eliminate the need to validate the type being cached (validate_type).* -  I am not sure why it would eliminate the need to validate the type being cached. We still want to make sure a developer doesn't try retrieving from an undefined cache, or there will be an ugly hard to understand con_cache error

 * *I'm not sure I see the need for a clear_local vs. simply a clear. Anytime we need to clear a cached object, we should clear globally and replace locally. If you want to keep the logic for local clearing separate, let's make it a private method.* - 'clear' is what is called by outside modules whenever they want to clear a value. This includes publishing a message to other managers to clear their local cache. 'clear_local' is what is called when a manager receives a message via rabbitmq telling it to clear. At this point, we can't call clear, or it will broadcast it out again, so we need a version of clear that doesn't broadcast. We also clear local immediately on the manager that initially gets the call so it doesn't return control to the caller with a potentially stale cache.

 * *I'm not sure I see the need for wipe_all_caches. It looks like the only place that's cached is during tests, but the tests could basically execute this logic. For a Manager developer, I think it would be confusing to see these last couple of methods without a reason to call them in development.* - I went the route of keeping this code in the ResourceCache module instead of copy/pasting the ugly code to all of the test modules that will be needing this code going forward. I will update the docs to note that this is only to be used in tests.

**Comment by msawka** [comment]
* Don't forget to update the file names to match the module names
* [Here](https://github.com/OpenAperture/manager/blob/resource_cache/lib/manager/messaging/manager_queue_subscriber.ex#L33-L47), condense this into a separate private function that will create the SystemEvent.  Also, we shouldn't need to use ManagerApi, as we have direct access to the db.  As I mentioned earlier, the other components need to be cleaned up so it's not just a copy/paste of the huge code block defining the event.
* Re requiring a specific type:  I think mis-undestood how ConCache worked, in that you're required to spin up a separate ConCache process for each type.  Can we investigate dynamically creating a ConCache based on the type, as needed (part of the get); I think it's possible to add a supervisor dynamically, or if not create a GenServer that controls the set of available caches (based on the key).  I'd still like to avoid having to hard-code the list of available caches if we can avoid it.  It seems like a developer could easily forget to add their "cache type" to the list, and I'm not sure what the advantage is to the developer for requiring a specific list of cachable models.
* Re clear vs. clear_local:  would it make sense to only clear your cache when you receive a message from rabbitmq?  That should simplify the logic so that when someone calls clear, you simply publish a message, and you clear your cache anytime you receive a message.  This would eliminiate the need for "if it's local, do this, if it's remote, do that"
* Re wipe_all_caches:  Can we define a module in [test_helper](https://github.com/OpenAperture/manager/blob/resource_cache/test/test_helper.exs) that takes care of this?  That would keep "production" code and "test" code separate.

**Comment by TheFirstAvenger** [comment]
* *Re requiring a specific type* I had originally thought of making it auto-create the caches, however the reason I went with requiring a specific type is that it prevents someone from accidentally assuming that a type is covered by the cache when it is not. Remember that for every type we add to the cache, the entire codebase needs to be checked and modified so that all writes clear the cache. Let's say a developer is adding a new feature for workflows, and pulls the workflow out of the cache, but none of the other places where we use workflows honor or clear the cache. This will lead to confusing issues that probably won't even appear in their unit tests, as all of their code will be using the cache correctly. Having a list of "valid types" which fails immediately when a type that hasn't been set up for cache is used would prevent this. If they truly want to use the cache for workflows, then it will be on them to scour the codebase and ensure that workflows across the board maintain the cache correctly, and add it to the list of valid types.

 * *clear vs clear_local This would eliminiate the need for "if it's local, do this, if it's remote, do that"*: we still need a separate clear and clear_local call. We need one that controllers will call after they update the database, which will publish the clear message, and a second one for the subscriber that is listening for the rabbitmq message to call when it receives a message. The subscriber can't call the first function, or it will trigger another message back out to rabbitmq, putting it in an infinite loop. As far as calling the local version right away instead of waiting for a message back, if we don't immediately clear the local cache, and instead wait for the asynchronous rabbitmq message to go out to the queues and come back, then we could potentially pass control back to the caller who just asked the cache to be cleared, except the cache is still dirty. In a case where we are replacing an entity, this could be dangerous, as code immediately following the create/update could request that new entity and get the old one.

**Pull request closed without merging**
